# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('location',)},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='picha_category',
            new_name='picture_category',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='picha_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='image',
            name='picha_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='picha.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
