# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0002_auto_20190719_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
