# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0003_auto_20190719_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
